In [1]:
import os

test_dir = os.getcwd()
lib_dir = test_dir+"/../lib/"

os.chdir(lib_dir)
import algorithms
import numpy as np


###### Parameters

In [2]:
N = 50  # number of nodes
exponent = -0.5 # exponent of laplacian method

alpha = 0.2 # alpha of the propagation

In [7]:
matrix = np.array([[1,2],[1,2]])
strength = matrix.sum(axis=0)
lap = algorithms.normalize_by_strength(matrix, exponent, strength)

print(strength.shape)
print(lap)
print(np.sign(0-1e-10))

(2,)
[[0.5        0.70710678]
 [0.35355339 0.5       ]]
-1.0


In [15]:
network = algorithms.Network(np.array([[0, 1, 1, 0],
                      [1, 0, 1, 0],
                      [1, 1, 0, 1],
                      [0, 0, 1, 0]]))
seed_matrix = np.eye(4)

score_matrix = algorithms.Propagator.label_propagator(network, 
                                           seed_matrix, 
                                           alpha=alpha, 
                                           max_iter=1, 
                                           exponent=exponent)
print(score_matrix)

[[0.8149547  0.10186934 0.07568778 0.        ]
 [0.10186934 0.8149547  0.07568778 0.        ]
 [0.08317597 0.08317597 0.74158576 0.12613198]
 [0.         0.         0.10703868 0.87386802]]


In [21]:
4-score_matrix.argsort(axis=0).argsort(axis=0)

array([[1, 2, 4, 4],
       [2, 1, 3, 3],
       [3, 3, 1, 2],
       [4, 4, 2, 1]])

### Time of propagator

In [13]:
import matplotlib.pylab as plt

In [12]:
def propagator_time(number_of_nodes, max_iter):
N = 1000
x = np.random.uniform(size=(N, N))
n = algorithms.Network((x+x.T) >= 1)
seed_matrix = np.eye(N)

from time import time

t0 = time()
score_matrix = algorithms.Propagator.label_propagator(n, seed_matrix, alpha=0.8, max_iter=100, exponent=exponent)
print(time() - t0)

Test time
0.31139135360717773
