In [1]:
import os

test_dir = os.getcwd()
lib_dir = test_dir+"/../lib/"

os.chdir(lib_dir)
import algorithms
import evaluators
import numpy as np


###### Parameters

In [18]:
np.random.seed(1)
n_targets = 10
N = 50  # number of nodes

laplacian_exponent = -0.5  # exponent of laplacian method
alpha = 0.2 # alpha of the propagation

max_fpr = 0.1
max_iter = 100

In [19]:
# x = np.random.uniform(size=(N, N))
# network = algorithms.Network(1*((x + x.T) >= 1))
x = np.roll(np.eye(N), 1, axis=0)
network = algorithms.Network(x+x.T)
network = algorithms.Network(x)
print(network)

mode: adjacency 
 value: 
 [[0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [26]:
seeds_matrix = np.eye(N)
targets_list = [np.roll(np.arange(N), -n)[1:(n_targets+1)] for n in range(N)]

p1 = 0.7
p = np.repeat((1-p1)/(n_targets-1), n_targets-1)
p = np.insert(p, 0, p1)
print(p)
true_targets = [[int(np.random.choice(targets, size=1, p=p))] for targets in targets_list]

print("Target list:")
print(targets_list)
print("True targets")
print(true_targets)

[0.7        0.03333333 0.03333333 0.03333333 0.03333333 0.03333333
 0.03333333 0.03333333 0.03333333 0.03333333]
Target list:
[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13]), array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]), array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15]), array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16]), array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17]), array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]), array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21]), array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22]), array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23]), array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24]), array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25]), array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26]), array([18, 19, 20, 21, 22, 23, 24, 25, 2

In [27]:
evalauc = evaluators.AUROClinkage(seeds_matrix, 
                                  targets_list, 
                                  true_targets, 
                                  alpha=alpha, 
                                  tol=1e-08, 
                                  max_iter=max_iter, 
                                  max_fpr=max_fpr,
                                  laplacian_exponent=laplacian_exponent)
auc = evalauc.evaluate(network)


print("AUC: {:.5f}".format(auc))

Network already in laplacian form. 
 Aborting conversion.
AUC: 0.53509
